# These are supported funding model platforms

#github: [jrquick17] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: jrquick17 # Replace with a single Patreon username
#ko_fi: # Replace with a single Ko-fi username
#liberapay: # Replace with a single Liberapay username
issuehunt: jrquick17 # Replace with a single IssueHunt username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
